# Install required packages for the IMDb project - do this before running the entire project with make

install.packages("readr")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("here")
install.packages("vroom")
install.packages("broom")
install.packages("ordinal")
install.packages("webshot2")
install.packages("modelsummary")
install.packages("here")
install.packages("gridExtra")
